compilers:
# compilers automatically found by spack compiler find 
# on cray list a lot of unused and not useful 
# compilers hence we do not here 
# list all that are found. 

# cray stack is not built with this one (eg libsci), 
# so using it results in link errors
#- compiler:
#    spec: gcc@7.5.0
#    paths:
#      cc: /usr/bin/gcc
#      cxx: /usr/bin/g++
#      f77: /usr/bin/gfortran
#      fc: /usr/bin/gfortran
#    flags: {}
#    operating_system: sles15
#    target: any
#    modules:
#    - craype-network-ofi
#    environment: {}
#    extra_rpaths: []

# On Shasta, need to list explicit paths 
# as well as default modules 
# note that the defaults are 
# craype craype-<arch> craype-network-ofi
# for testing, craype-x86-rome
# Might also want to limit arch as by default
# cray wrapper is always adding -march=znver2
# 
# Note also the addition of default flags

# gnu compilers 
- compiler:
    spec: gcc@11.2.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags:
      cflags: -O3
      cxxflags: -O3
      cppflags: -O3
      fflags: -O3 -fallow-argument-mismatch
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/11.2.0
    - craype
    - craype-x86-milan
    - craype-network-ofi
    environment: {}
    extra_rpaths: []

- compiler:
    spec: gcc@12.1.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags:
      cflags: -O3
      cxxflags: -O3
      cppflags: -O3
      fflags: -O3 -fallow-argument-mismatch
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/12.1.0
    - craype
    - craype-x86-milan
    - craype-network-ofi
    environment: {}
    extra_rpaths: []


# similar to above but has debugging flags
# these must be defined as a different version
# by convention we add debug to the name
- compiler:
    spec: gcc@11.2.0debug
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags:
      cflags: -O0 -g3 -pg -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all -fsanitize=float-divide-by-zero -fsanitize=float-cast-overflow -fno-sanitize=null -fno-sanitize=alignment
      cxxflags: -O0 -g3 -pg -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all -fsanitize=float-divide-by-zero -fsanitize=float-cast-overflow -fno-sanitize=null -fno-sanitize=alignment
      cppflags: -O0 -g3 -pg -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all -fsanitize=float-divide-by-zero -fsanitize=float-cast-overflow -fno-sanitize=null -fno-sanitize=alignment
      fflags: -O0 -g3 -pg -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all -fsanitize=float-divide-by-zero -fsanitize=float-cast-overflow -fno-sanitize=null -fno-sanitize=alignment
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/11.2.0
    - craype
    - craype-x86-milan
    - craype-network-ofi
    environment: {}
    extra_rpaths: []

# similar to above but has profiling flags
# these must be defined as a different version
# by convention we add profile to the name
- compiler:
    spec: gcc@11.2.0profile
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags:
      cflags: -O3 -g -fopt-info-all
      cxxflags: -O3 -g -fopt-info-all
      cppflags: -O3 -g -fopt-info-all
      fflags: -O3 -g -fallow-argument-mismatch -fopt-info-all
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/11.2.0
    - craype
    - craype-x86-rome
    - craype-network-ofi
    environment: {}
    extra_rpaths: []

- compiler:
    spec: gcc@11.2.0noflags
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-gnu
    - gcc/11.2.0
    - craype
    - craype-x86-milan
    - craype-network-ofi
    environment: {}
    extra_rpaths: []

# cray compilers 
- compiler:
    spec: cce@14.0.3
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags:
      cflags: -O3
      cxxflags: -O3
      cppflags: -O3
      fflags: -O3
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-cray
    - cce/14.0.3
    - craype
    - craype-x86-milan
    - craype-network-ofi
    environment: {}
    extra_rpaths: []

- compiler:
    spec: cce@14.0.3noflags
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn 
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-cray
    - cce/14.0.3
    - craype
    - craype-x86-milan
    - craype-network-ofi
    environment: {}
    extra_rpaths: []

# amd compilers 
- compiler:
    spec: aocc@3.2.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags:
      cflags: -O3
      cxxflags: -O3
      cppflags: -O3
      fflags: -O3 
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-aocc
    - aocc/3.2.0
    - craype
    - craype-x86-milan
    - craype-network-ofi
    environment: {}
    extra_rpaths: []

- compiler:
    spec: aocc@3.2.0noflags
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    operating_system: sles15
    target: any
    modules:
    - PrgEnv-aocc
    - aocc/3.2.0
    - craype
    - craype-x86-milan
    - craype-network-ofi
    environment: {}
    extra_rpaths: []

